Turns out testing brings out a lot of bugs.
ICMP still not working, the server logs a "Authenticate/Decrypt packet
error: packet HMAC authentication failed" error. It is really nice
that the server is seeing our packets, but still figuring out how to
get a properly authenticated packet.